modLoader = "javafml"
loaderVersion = "[4,)"
license = "Insert License Here"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Euclid's Elements"
authors = "Solstice"
description = "W.I.P."
displayURL="https://github.com/Solstace-MC/Euclids-Elements"
logoFile = "assets/${mod_id}/icon.png"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"
