on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Change Version
              run: sed -i 's/mod_version=.*/mod_version=${{ github.event.release.tag_name }}/g' gradle.properties

            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 21
                  cache: "gradle"
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Build Project
              run: ./gradlew clean build
            - name: Publish Mod
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: "${{ vars.MODRINTH_ID }}"
                  modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
                  modrinth-version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
                  github-tag: "${{ github.event.release.tag_name }}"
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

                  name: "${{ github.event.release.name }}"
                  version: "${{ github.event.release.tag_name }}"
                  version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
                  changelog: "${{ github.event.release.body }}"

                  game-versions: |
                      1.21.1
                  dependencies: |
                      fabric-api
            - name: Publish Modules
              run: ./gradlew publish
              env:
                  MAVEN_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.CLOUDSMITH_TOKEN }}
